-- 全テーブルのDATETIME(3)をDATETIMEに変更

-- calendar_events
ALTER TABLE calendar_events 
  MODIFY COLUMN startDate DATETIME NOT NULL,
  MODIFY COLUMN endDate DATETIME NOT NULL,
  MODIFY COLUMN createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- companies
ALTER TABLE companies
  MODIFY COLUMN establishedDate DATETIME,
  MODIFY COLUMN createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- engineer_users
ALTER TABLE engineer_users
  MODIFY COLUMN birthDate DATETIME,
  MODIFY COLUMN createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- projects
ALTER TABLE projects
  MODIFY COLUMN customerBirthDate DATETIME NOT NULL,
  MODIFY COLUMN firstInquiryDate DATETIME NOT NULL,
  MODIFY COLUMN workDate DATETIME,
  MODIFY COLUMN receptionDate DATETIME,
  MODIFY COLUMN orderDate DATETIME,
  MODIFY COLUMN expectedCompletionDate DATETIME,
  MODIFY COLUMN completionDate DATETIME,
  MODIFY COLUMN revisitDateTime DATETIME,
  MODIFY COLUMN roofingDate DATETIME,
  MODIFY COLUMN demolitionDate DATETIME,
  MODIFY COLUMN deliveryDate DATETIME,
  MODIFY COLUMN shipmentDate DATETIME,
  MODIFY COLUMN surveyRequestDate DATETIME,
  MODIFY COLUMN surveyDate DATETIME,
  MODIFY COLUMN reSurveyDate DATETIME,
  MODIFY COLUMN constructionDate DATETIME,
  MODIFY COLUMN remainingWorkDate DATETIME,
  MODIFY COLUMN createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- main_info
ALTER TABLE main_info
  MODIFY COLUMN roofingDate DATETIME,
  MODIFY COLUMN demolitionDate DATETIME,
  MODIFY COLUMN deliveryDate DATETIME,
  MODIFY COLUMN shipmentDate DATETIME,
  MODIFY COLUMN surveyRequestDate DATETIME,
  MODIFY COLUMN surveyDate DATETIME,
  MODIFY COLUMN reSurveyDate DATETIME,
  MODIFY COLUMN constructionDate DATETIME,
  MODIFY COLUMN remainingWorkDate DATETIME,
  MODIFY COLUMN createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- reports
ALTER TABLE reports
  MODIFY COLUMN remainingWorkDate DATETIME,
  MODIFY COLUMN createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- project_files
ALTER TABLE project_files
  MODIFY COLUMN createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- report_files
ALTER TABLE report_files
  MODIFY COLUMN createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- monthly_expenses
ALTER TABLE monthly_expenses
  MODIFY COLUMN createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- inventory_items
ALTER TABLE inventory_items
  MODIFY COLUMN createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- inventory_price_history
ALTER TABLE inventory_price_history
  MODIFY COLUMN effectiveFrom DATETIME NOT NULL,
  MODIFY COLUMN effectiveTo DATETIME,
  MODIFY COLUMN createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- selling_price_types
ALTER TABLE selling_price_types
  MODIFY COLUMN createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- pickup_materials
ALTER TABLE pickup_materials
  MODIFY COLUMN createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- notifications
ALTER TABLE notifications
  MODIFY COLUMN createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- vaxal_users
ALTER TABLE vaxal_users
  MODIFY COLUMN createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
