-- CreateTable
CREATE TABLE `MainInfo` (
    `id` VARCHAR(191) NOT NULL,
    `projectNumber` VARCHAR(191) NOT NULL,
    `constructionNotes` TEXT NULL,
    `contractorName` VARCHAR(191) NULL,
    `contractorPhone` VARCHAR(191) NULL,
    `contractorNotes` TEXT NULL,
    `receptionStaff` VARCHAR(191) NULL,
    `receptionStaffPhone` VARCHAR(191) NULL,
    `salesStaff` VARCHAR(191) NULL,
    `salesStaffPhone` VARCHAR(191) NULL,
    `constructionStaff` VARCHAR(191) NULL,
    `constructionStaffPhone` VARCHAR(191) NULL,
    `staffNotes` TEXT NULL,
    `roofingDate` DATETIME(3) NULL,
    `demolitionDate` DATETIME(3) NULL,
    `buildingType` ENUM('MANSION', 'DETACHED_HOUSE', 'APARTMENT', 'OTHER') NULL,
    `installationFloor` VARCHAR(191) NULL,
    `installationLocation` TEXT NULL,
    `keyboxNumber` VARCHAR(191) NULL,
    `storageLocation` VARCHAR(191) NULL,
    `parkingSpace` TEXT NULL,
    `buildingNotes` TEXT NULL,
    `productCategory` VARCHAR(191) NULL,
    `productSeries` VARCHAR(191) NULL,
    `deliveryDate` DATETIME(3) NULL,
    `shipmentDate` DATETIME(3) NULL,
    `productNotes` TEXT NULL,
    `deliveryTime` VARCHAR(191) NULL,
    `deliverySpecification` VARCHAR(191) NULL,
    `deliveryLocation` VARCHAR(191) NULL,
    `deliveryNotes` TEXT NULL,
    `surveyRequestDate` DATETIME(3) NULL,
    `surveyDate` DATETIME(3) NULL,
    `surveyTime` VARCHAR(191) NULL,
    `surveyCompany` VARCHAR(191) NULL,
    `surveyStaff` VARCHAR(191) NULL,
    `reSurveyDate` DATETIME(3) NULL,
    `surveyNotes` TEXT NULL,
    `constructionDate` DATETIME(3) NULL,
    `constructionCompany` VARCHAR(191) NULL,
    `constructionStaffName` VARCHAR(191) NULL,
    `constructionPhone` VARCHAR(191) NULL,
    `constructionEmail` VARCHAR(191) NULL,
    `remainingWorkDate` DATETIME(3) NULL,
    `constructionInfoNotes` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `projectId` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `MainInfo_projectNumber_key`(`projectNumber`),
    UNIQUE INDEX `MainInfo_projectId_key`(`projectId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `MainInfo` ADD CONSTRAINT `MainInfo_projectId_fkey` FOREIGN KEY (`projectId`) REFERENCES `Project`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
