-- AlterTable
ALTER TABLE `calendar_events` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT NOW(),
    MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT NOW() ON UPDATE NOW();

-- AlterTable
ALTER TABLE `companies` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT NOW(),
    MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT NOW() ON UPDATE NOW();

-- AlterTable
ALTER TABLE `engineer_users` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT NOW(),
    MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT NOW() ON UPDATE NOW();

-- AlterTable
ALTER TABLE `inventory_items` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT NOW(),
    MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT NOW() ON UPDATE NOW();

-- AlterTable
ALTER TABLE `inventory_price_history` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT NOW(),
    MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT NOW() ON UPDATE NOW();

-- AlterTable
ALTER TABLE `main_info` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT NOW(),
    MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT NOW() ON UPDATE NOW();

-- AlterTable
ALTER TABLE `monthly_expenses` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT NOW(),
    MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT NOW() ON UPDATE NOW();

-- AlterTable
ALTER TABLE `notifications` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT NOW(),
    MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT NOW() ON UPDATE NOW();

-- AlterTable
ALTER TABLE `pickup_materials` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT NOW(),
    MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT NOW() ON UPDATE NOW();

-- AlterTable
ALTER TABLE `project_files` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT NOW(),
    MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT NOW() ON UPDATE NOW();

-- AlterTable
ALTER TABLE `projects` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT NOW(),
    MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT NOW() ON UPDATE NOW();

-- AlterTable
ALTER TABLE `report_files` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT NOW(),
    MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT NOW() ON UPDATE NOW();

-- AlterTable
ALTER TABLE `reports` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT NOW(),
    MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT NOW() ON UPDATE NOW();

-- AlterTable
ALTER TABLE `selling_price_types` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT NOW(),
    MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT NOW() ON UPDATE NOW();

-- AlterTable
ALTER TABLE `vaxal_users` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT NOW(),
    MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT NOW() ON UPDATE NOW();
